package com.example.quizzfirstprojecthadp.game

class Question (
    val id: Int,
    val question: String,
    val answer: String,
    val option2: String,
    val option3: String,
    val option4: String)
{
    companion object {
        val listOfQuestion = listOf(
            Question(0,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(1,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(2,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(3,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(4,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(5,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(6,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(7,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(8,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(9,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(10,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(11,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(12,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(13,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(14,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(15,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(16,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(17,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(18,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(19,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(20,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(21,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(22,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(23,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(24,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(25,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(26,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(27,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(28,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(29,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(30,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(31,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(32,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(33,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(34,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(35,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(36,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(37,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(38,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(39,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(40,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(41,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(42,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(43,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(44,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(45,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(46,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(47,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(48,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(49,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(50,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(51,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(52,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(53,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(54,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(55,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(56,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(57,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(58,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman"),
            Question(59,"¿Contra quién pelea Baki antes de pelear con su padre?","Mohammad Alai Jr.","Floyd Maywother","Mohammad Alai","The Boogerman")
        )
    }
}
